# Generated by Django 5.2 on 2025-08-22 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_remove_location_unique_location_and_more"),
        ("department", "0003_alter_department_access_department"),
        ("plugin", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="plugin",
            name="either_username_password_or_api_key_required",
        ),
        migrations.AddConstraint(
            model_name="plugin",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        models.Q(
                            ("password__isnull", False), ("username__isnull", False)
                        ),
                        models.Q(("username__exact", ""), _negated=True),
                        models.Q(("password__exact", ""), _negated=True),
                    ),
                    models.Q(
                        models.Q(("api_key__isnull", False)),
                        models.Q(("api_key__exact", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="either_username_password_or_api_key_required",
                violation_error_message="Either username and password or api_key must be provided.",
            ),
        ),
    ]
