# Generated by Django 5.2 on 2025-08-22 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "plugin",
            "0002_remove_plugin_either_username_password_or_api_key_required_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="plugin",
            name="access_level",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
    ]
